Repository kubernetes-simulator/simulator, pull requests merged in 2019-11, with the labels that each got.

#86 Typo fix.
  attack/scripts/bashrc
Labels: documentation, low

#95 Standardise Starting Points
  simulation-scripts/scenario/container-ambush/tasks.yaml
  simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml
  simulation-scripts/scenario/container-phalanx-formation/tasks.yaml
  simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml
  simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml
  simulation-scripts/scenario/master-encirclement/tasks.yaml
  simulation-scripts/scenario/network-feint/tasks.yaml
  simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml
  simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml
  simulation-scripts/scenario/network-swarming/tasks.yaml
  simulation-scripts/scenario/node-amphibious-operations/tasks.yaml
  simulation-scripts/scenario/node-raiding/tasks.yaml
  simulation-scripts/scenario/node-shock-tactics/tasks.yaml
  simulation-scripts/scenario/policy-echelon-formation/tasks.yaml
  simulation-scripts/scenario/policy-fire-support/tasks.yaml
  simulation-scripts/scenario/policy-force-dispersal/tasks.yaml
  simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml
  simulation-scripts/scenario/rbac-contact-drill/tasks.yaml
  simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml
  simulation-scripts/scenario/rbac-sangar/tasks.yaml
  simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml
  simulation-scripts/scenario/secret-high-ground/tasks.yaml
  simulation-scripts/scenario/secret-tank-desant/tasks.yaml
Labels: enhancement

#97 Reformat to YAML.
  docs/tasks-yaml-format.md
  simulation-scripts/scenario/container-ambush/tasks.yaml
  simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml
  simulation-scripts/scenario/container-phalanx-formation/tasks.yaml
  simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml
  simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml
  simulation-scripts/scenario/master-encirclement/tasks.yaml
  simulation-scripts/scenario/network-feint/tasks.yaml
  simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml
  simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml
  simulation-scripts/scenario/network-swarming/tasks.yaml
  simulation-scripts/scenario/node-amphibious-operations/tasks.yaml
  simulation-scripts/scenario/node-raiding/tasks.yaml
  simulation-scripts/scenario/node-shock-tactics/tasks.yaml
  simulation-scripts/scenario/policy-echelon-formation/tasks.yaml
  simulation-scripts/scenario/policy-fire-support/tasks.yaml
  simulation-scripts/scenario/policy-force-dispersal/tasks.yaml
  simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml
  simulation-scripts/scenario/rbac-contact-drill/tasks.yaml
  simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml
  simulation-scripts/scenario/rbac-sangar/tasks.yaml
  simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml
  simulation-scripts/scenario/secret-high-ground/tasks.yaml
  simulation-scripts/scenario/secret-tank-desant/tasks.yaml
Labels: enhancement

#98 feat: add CODEOWNERS file
  CODEOWNERS
Labels: enhancement, github, low

#96 feat(infra): tag AWS resources with the simulator bucket name
  terraform/deployments/AWS/main.tf
  terraform/deployments/AWS/providers.tf
Labels: enhancement, medium

#101 feat: mount working dirs for make run
  Makefile
Labels: enhancement

#104 Minor Corrections
  CODEOWNERS
  Makefile
Labels: bug, documentation

#105 feat(scen): Added start points for each task in each scenario
  docs/tasks-yaml-format.md
  simulation-scripts/scenario/container-ambush/tasks.yaml
  simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml
  simulation-scripts/scenario/container-phalanx-formation/tasks.yaml
  simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml
  simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml
  simulation-scripts/scenario/master-encirclement/tasks.yaml
  simulation-scripts/scenario/network-feint/tasks.yaml
  simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml
  simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml
  simulation-scripts/scenario/network-swarming/tasks.yaml
  simulation-scripts/scenario/node-amphibious-operations/tasks.yaml
  simulation-scripts/scenario/node-raiding/tasks.yaml
  simulation-scripts/scenario/node-shock-tactics/tasks.yaml
  simulation-scripts/scenario/policy-echelon-formation/tasks.yaml
  simulation-scripts/scenario/policy-fire-support/tasks.yaml
  simulation-scripts/scenario/policy-force-dispersal/tasks.yaml
  simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml
  simulation-scripts/scenario/rbac-contact-drill/tasks.yaml
  simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml
  simulation-scripts/scenario/rbac-sangar/tasks.yaml
  simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml
  simulation-scripts/scenario/secret-high-ground/tasks.yaml
  simulation-scripts/scenario/secret-tank-desant/tasks.yaml
Labels: medium

#106 Task difficulty
  pkg/scenario/scenario.go
  simulation-scripts/scenario/container-ambush/challenge.txt
  simulation-scripts/scenario/container-defeat-in-detail/challenge.txt
  simulation-scripts/scenario/container-phalanx-formation/challenge.txt
  simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt
  simulation-scripts/scenario/master-bait-and-bleed/challenge.txt
  simulation-scripts/scenario/master-encirclement/challenge.txt
  simulation-scripts/scenario/network-feint/challenge.txt
  simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt
  simulation-scripts/scenario/network-hedgehog-defence/challenge.txt
  simulation-scripts/scenario/network-swarming/challenge.txt
  simulation-scripts/scenario/node-amphibious-operations/challenge.txt
  simulation-scripts/scenario/node-raiding/challenge.txt
  simulation-scripts/scenario/node-shock-tactics/challenge.txt
  simulation-scripts/scenario/policy-echelon-formation/challenge.txt
  simulation-scripts/scenario/policy-fire-support/challenge.txt
  simulation-scripts/scenario/policy-force-dispersal/challenge.txt
  simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt
  simulation-scripts/scenario/rbac-contact-drill/challenge.txt
  simulation-scripts/scenario/rbac-flanking-maneuver/challenge.txt
  simulation-scripts/scenario/rbac-sangar/challenge.txt
  simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt
  simulation-scripts/scenario/secret-high-ground/challenge.txt
  simulation-scripts/scenario/secret-tank-desant/challenge.txt
  simulation-scripts/scenarios.yaml
Labels: enhancement, medium

#108 docs: Added a short .md about task difficulty
  docs/create-scenario.md
  docs/difficulty.md
Labels: documentation, low

#110 docs(make): update the output of make help to be consistent
  Makefile
Labels: documentation, low

#109 feat(scen): add difficulties to the scenarios
  simulation-scripts/scenario/container-ambush/challenge.txt
  simulation-scripts/scenario/container-defeat-in-detail/challenge.txt
  simulation-scripts/scenario/container-phalanx-formation/challenge.txt
  simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt
  simulation-scripts/scenario/master-bait-and-bleed/challenge.txt
  simulation-scripts/scenario/master-encirclement/challenge.txt
  simulation-scripts/scenario/network-feint/challenge.txt
  simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt
  simulation-scripts/scenario/network-hedgehog-defence/challenge.txt
  simulation-scripts/scenario/network-swarming/challenge.txt
  simulation-scripts/scenario/node-amphibious-operations/challenge.txt
  simulation-scripts/scenario/node-raiding/challenge.txt
  simulation-scripts/scenario/node-shock-tactics/challenge.txt
  simulation-scripts/scenario/policy-echelon-formation/challenge.txt
  simulation-scripts/scenario/policy-fire-support/challenge.txt
  simulation-scripts/scenario/policy-force-dispersal/challenge.txt
  simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt
  simulation-scripts/scenario/rbac-contact-drill/challenge.txt
  simulation-scripts/scenario/rbac-flanking-maneuver/challenge.txt
  simulation-scripts/scenario/rbac-sangar/challenge.txt
  simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt
  simulation-scripts/scenario/secret-high-ground/challenge.txt
  simulation-scripts/scenario/secret-tank-desant/challenge.txt
  simulation-scripts/scenarios.yaml
Labels: enhancement, medium

#111 fix(make): validate aws requirements before release or build
  Makefile
Labels: bug, low

#99 feat: change ssh mount path
  Makefile
  kubesim
Labels: low

#115 fix(tf): revert #96 as it was preventing tf init for new state
  terraform/deployments/AWS/main.tf
  terraform/deployments/AWS/providers.tf
Labels: bug, medium

#118 fix(scen): minor hints update and do not check keys for attack ssh functions
  attack/scripts/bashrc
  simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt
  simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml
Labels: low, short

#121 feat(tf): add kubectl config to internal node and update attack helpers
  attack/scripts/bashrc
  simulation-scripts/scenario/node-shock-tactics/challenge.txt
  terraform/deployments/AWS/main.tf
  terraform/modules/AWS/Bastion/cloud-config.tf
  terraform/modules/AWS/Bastion/cloud-config.yaml
  terraform/modules/AWS/Bastion/variables.tf
  terraform/modules/AWS/InternalNode/internal-config.tf
  terraform/modules/AWS/InternalNode/internal-config.yaml
  terraform/modules/AWS/InternalNode/main.tf
  terraform/modules/AWS/InternalNode/variables.tf
  terraform/modules/AWS/Kubernetes/master-cloud-config.yaml
  test/smoke.expect
Labels: enhancement, medium, short, terraform
